add_subdirectory(core)
add_subdirectory(usb)
add_subdirectory(device)
add_subdirectory(sim)
add_subdirectory(depth)
add_subdirectory(synth)
add_subdirectory(calib)
add_subdirectory(gpu)
add_subdirectory(depth_metal)
add_subdirectory(render)
add_subdirectory(fixtures)
add_subdirectory(track)
add_subdirectory(pipeline)
add_subdirectory(track_metal)
